version: '3'
services:
  nignx:
    image: nginx:latest
    container_name: gomoku_nginx
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ${P}/gomoku_env/templates/gomoku.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server
  client:
    image: node:latest
    container_name: gomoku_client
    expose:
      - 8080
    volumes:
      - type: bind
        source: ${P}/gomoku_client
        target: /home/gomoku_client
    command: bash -c "cd /home/gomoku_client && yarn install && yarn serve"
  server:
    image: python:latest
    container_name: gomoku_server
    expose:
      - 8000
    volumes:
      - type: bind
        source: ${P}/gomoku_server
        target: /home/gomoku_server
    depends_on:
      - postgres
      - redis
    command: bash -c "cd /home/gomoku_server && pip install --upgrade pip && pip install -r requirements.txt && cd src && python manage.py runserver 0:8000 --settings=settings.develop"
  postgres:
    image: postgres:latest
    container_name: gomoku_db
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
  redis:
    image: redis:latest
    container_name: gomoku_redis
    expose:
      - 6379
